#!/usr/bin/env python3
"""Generate extension/src/seed-names.js from data/seeds.json.

The extension has to recognise a seed by whatever name the game happens to use, so it
ships a lookup table built from the same dataset the web app uses.

    python scripts/build-extension-data.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SEEDS = ROOT / "data" / "seeds.json"
TARGET = ROOT / "extension" / "src" / "seed-names.js"


def normalise(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", value.lower())


def main() -> None:
    seeds = json.loads(SEEDS.read_text(encoding="utf-8"))["seeds"]

    lookup: dict[str, str] = {}
    for seed in seeds:
        for alias in (seed["name"], seed["id"], re.sub(r"\s*seeds?$", "", seed["name"], flags=re.I)):
            key = normalise(alias)
            if key:
                lookup.setdefault(key, seed["id"])

    body = json.dumps(lookup, indent=2, sort_keys=True)
    TARGET.write_text(
        "/* Generated by scripts/build-extension-data.py — do not edit by hand. */\n"
        "// Maps a normalised seed name (lowercase, letters and digits only) to a catalogue id.\n"
        f"globalThis.BIOPLOT_SEED_IDS = {body}\n",
        encoding="utf-8",
    )
    print(f"wrote {TARGET.relative_to(ROOT)} with {len(lookup)} aliases")


if __name__ == "__main__":
    main()
